### ISSUE TITLE
Where can I find the code for the web challenges?

### ISSUE THREAD

**Issue by PhilParisot** [defund/ctf#1]
Where can I find the code for the web challenges?

I tried to do the challenges but it looks like the web challenges aren't live or hosted anymore.

Thanks!

**Comment by defund** [comment]
We have a challenge archive here: https://github.com/blairsec/challenges/tree/master/angstromctf/2019/web
Hope you enjoy the challenges!

**Comment by PhilParisot** [comment]
Woot! Thank you!
